GET http://localhost:5184/todos

###

POST http://localhost:5184/todos
content-Type: application/json

{
    "id":1,
    "name":"Testing",
    "dueDate":"2025-03-24T00:00:00Z",
    "isCompleted": false
}

###